/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.FornecedorDAO;
import model.Fornecedor;
import util.Validar;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author Gustavo Aquino
 */
public class Fornecedores extends javax.swing.JFrame {
    /**
     * Creates new form Fornecedores
     */
    public Fornecedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Nome = new javax.swing.JLabel();
        TextNomeFornecedor = new javax.swing.JTextField();
        CNPJ = new javax.swing.JLabel();
        TextCnpjFornecedor = new javax.swing.JTextField();
        IE = new javax.swing.JLabel();
        IEtextFornecedor = new javax.swing.JTextField();
        Endereco = new javax.swing.JLabel();
        TextEnderecoFornecedor = new javax.swing.JTextField();
        CEP = new javax.swing.JLabel();
        TextCepFornecedor = new javax.swing.JTextField();
        ID = new javax.swing.JLabel();
        BtnDeletarForncedor = new javax.swing.JButton();
        BtnAdicionarForncedor = new javax.swing.JButton();
        BtnAtualizarForncedor = new javax.swing.JButton();
        BtnListarForncedor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Sair = new javax.swing.JButton();
        TextIdFornecedor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Fornecedores");

        Nome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Nome.setText("Nome:");

        CNPJ.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CNPJ.setText("CNPJ:");

        IE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IE.setText("IE:");

        Endereco.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Endereco.setText("Endereço:");

        CEP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CEP.setText("CEP:");

        ID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ID.setText("ID:");

        BtnDeletarForncedor.setText("Deletar");
        BtnDeletarForncedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnDeletarForncedorMouseClicked(evt);
            }
        });

        BtnAdicionarForncedor.setText("Adicionar");
        BtnAdicionarForncedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAdicionarForncedorMouseClicked(evt);
            }
        });

        BtnAtualizarForncedor.setText("Atualizar");
        BtnAtualizarForncedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAtualizarForncedorMouseClicked(evt);
            }
        });

        BtnListarForncedor.setText("Listar");
        BtnListarForncedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnListarForncedorMouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"default", "default", "default", "default", "default", "default"}
            },
            new String [] {
                "Nome", "CNPJ", "IE", "CEP", "Endereço", "ID"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Sair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Sair.setText("<");
        Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairMouseClicked(evt);
            }
        });
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Sair)
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BtnAdicionarForncedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnAtualizarForncedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnListarForncedor, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CNPJ)
                                    .addComponent(IE)
                                    .addComponent(CEP))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextCepFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TextCnpjFornecedor)
                                        .addComponent(IEtextFornecedor))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Endereco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextEnderecoFornecedor)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(ID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextIdFornecedor))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnDeletarForncedor)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Sair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ID)
                        .addComponent(TextIdFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CNPJ)
                    .addComponent(TextCnpjFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IE)
                    .addComponent(IEtextFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CEP)
                    .addComponent(TextCepFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextEnderecoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Endereco))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnDeletarForncedor)
                    .addComponent(BtnListarForncedor)
                    .addComponent(BtnAtualizarForncedor)
                    .addComponent(BtnAdicionarForncedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SairActionPerformed

    private void SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseClicked
    Menu menu = new Menu();
    this.dispose();
    menu.setVisible(true);
    // TODO add your handling code here:
    }//GEN-LAST:event_SairMouseClicked

    private void BtnAdicionarForncedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAdicionarForncedorMouseClicked

        String nome = TextNomeFornecedor.getText();
        String cnpj = TextCnpjFornecedor.getText();
        String ie = IEtextFornecedor.getText();
        String cep = TextCepFornecedor.getText();
        String endereco = TextEnderecoFornecedor.getText();

        Fornecedor fornecedor = new Fornecedor(0,nome, cnpj, ie, endereco, cep);
        if(Validar.validarCNPJ(cnpj)) {
            new FornecedorDAO().save(fornecedor);
            JOptionPane.showMessageDialog(this, "Fornecedor salvo!");
        }else {
            JOptionPane.showMessageDialog(null, "Preencha os campos corretamente");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAdicionarForncedorMouseClicked

    private void BtnAtualizarForncedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAtualizarForncedorMouseClicked

        String nome = TextNomeFornecedor.getText();
        String cnpj = TextCnpjFornecedor.getText();
        String ie = IEtextFornecedor.getText();
        String cep = TextCepFornecedor.getText();
        String endereco = TextEnderecoFornecedor.getText();
        String id = TextIdFornecedor.getText();

        Fornecedor fornecedor = new Fornecedor(Integer.parseInt(id), nome, cnpj, ie, endereco, cep);
        if(Validar.validarCNPJ(cnpj)) {
            new FornecedorDAO().update(fornecedor);
            JOptionPane.showMessageDialog(this, "Atualizado com sucesso");
        }else {
            JOptionPane.showMessageDialog(null, "Preencha os campos corretamente");
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAtualizarForncedorMouseClicked

    private void BtnListarForncedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnListarForncedorMouseClicked
        DefaultTableModel tabelaForncedor = (DefaultTableModel) jTable1.getModel();

        Integer numero = tabelaForncedor.getRowCount();

        if(numero > 0){
            for(int i = 0; i < numero; i++){
                tabelaForncedor.removeRow(0);
            }
            List<Fornecedor> fornecedores = new FornecedorDAO().getFornecedores();

            for(Fornecedor fornecedor : fornecedores){
                Object[] dados = {fornecedor.getNome(), fornecedor.getCnpj(), fornecedor.getIe(), fornecedor.getcep(), fornecedor.getEndereco(), fornecedor.getId()};
                tabelaForncedor.addRow(dados);
            }
        }
    }


        // TODO add your handling code here:
    //GEN-LAST:event_BtnListarForncedorMouseClicked

    private void BtnDeletarForncedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDeletarForncedorMouseClicked
        String id = TextIdFornecedor.getText();

        Fornecedor fornecedor = new Fornecedor(Integer.parseInt(id),null, null, null, null, null);
        new FornecedorDAO().deleteById(fornecedor.getId());
        JOptionPane.showMessageDialog(this, "Deletado com sucesso");

        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDeletarForncedorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fornecedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdicionarForncedor;
    private javax.swing.JButton BtnAtualizarForncedor;
    private javax.swing.JButton BtnDeletarForncedor;
    private javax.swing.JButton BtnListarForncedor;
    private javax.swing.JLabel CEP;
    private javax.swing.JLabel CNPJ;
    private javax.swing.JLabel Endereco;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel IE;
    private javax.swing.JTextField IEtextFornecedor;
    private javax.swing.JLabel Nome;
    private javax.swing.JButton Sair;
    private javax.swing.JTextField TextCepFornecedor;
    private javax.swing.JTextField TextCnpjFornecedor;
    private javax.swing.JTextField TextEnderecoFornecedor;
    private javax.swing.JTextField TextIdFornecedor;
    private javax.swing.JTextField TextNomeFornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
