/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.FuncionarioDAO;
import model.Funcionario;
import util.Validar;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author Samsung
 */
public class Funcionarios extends javax.swing.JFrame {

    /**
     * Creates new form Funcionarios
     */
    public Funcionarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Nome = new javax.swing.JLabel();
        TextNomeFuncionario = new javax.swing.JTextField();
        RGF = new javax.swing.JLabel();
        TextRgfFuncionario = new javax.swing.JTextField();
        RG = new javax.swing.JLabel();
        TextRgFuncionario = new javax.swing.JTextField();
        CPF = new javax.swing.JLabel();
        TextCpfFuncionario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BtnDeletarFuncionario = new javax.swing.JButton();
        BtnAdicionarFuncionario = new javax.swing.JButton();
        BtnAtualiazarFuncionario = new javax.swing.JButton();
        BtnListarFuncionarios = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Sair = new javax.swing.JButton();
        TextIDFuncionarios = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Funcionarios");

        Nome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Nome.setText("Nome:");

        RGF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RGF.setText("RGF:");

        RG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RG.setText("RG:");

        CPF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CPF.setText("CPF:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("ID:");

        BtnDeletarFuncionario.setText("Deletar");
        BtnDeletarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnDeletarFuncionarioMouseClicked(evt);
            }
        });

        BtnAdicionarFuncionario.setText("Adicionar");
        BtnAdicionarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAdicionarFuncionarioMouseClicked(evt);
            }
        });

        BtnAtualiazarFuncionario.setText("Atualizar");
        BtnAtualiazarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAtualiazarFuncionarioMouseClicked(evt);
            }
        });

        BtnListarFuncionarios.setText("Listar");
        BtnListarFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnListarFuncionariosMouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"default", "default", "default", "default", "default"},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "RGF", "RG", "CPF", "ID"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Sair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Sair.setText("<");
        Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(Sair)
                        .addGap(108, 108, 108)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Nome)
                                .addGap(12, 12, 12)
                                .addComponent(TextNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RGF)
                                    .addComponent(RG)
                                    .addComponent(CPF))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextRgFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(TextCpfFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(TextRgfFuncionario))))))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextIDFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(BtnAdicionarFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnAtualiazarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnListarFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnDeletarFuncionario)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sair)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome)
                    .addComponent(TextNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(TextIDFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RGF)
                    .addComponent(TextRgfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RG)
                    .addComponent(TextRgFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CPF)
                    .addComponent(TextCpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAdicionarFuncionario)
                    .addComponent(BtnAtualiazarFuncionario)
                    .addComponent(BtnListarFuncionarios)
                    .addComponent(BtnDeletarFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAdicionarFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAdicionarFuncionarioMouseClicked
        String nome = TextNomeFuncionario.getText();
        String rgf = TextRgfFuncionario.getText();
        String rg = TextRgFuncionario.getText();
        String cpf = TextCpfFuncionario.getText();

        Funcionario funcionario = new Funcionario(0,nome,rgf,rg,cpf);
        if(Validar.validarCPF(cpf)){
            new FuncionarioDAO().save(funcionario);
            JOptionPane.showMessageDialog(this, "Funcionário salvo");
        } else {
            JOptionPane.showMessageDialog(null, "Preencha os campos corretamente");
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAdicionarFuncionarioMouseClicked

    private void SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseClicked
        Menu menu = new Menu();
        this.dispose();
        menu.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_SairMouseClicked

    private void BtnAtualiazarFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAtualiazarFuncionarioMouseClicked

        String nome = TextNomeFuncionario.getText();
        String rgf = TextRgfFuncionario.getText();
        String rg = TextRgFuncionario.getText();
        String cpf = TextCpfFuncionario.getText();
        String id = TextIDFuncionarios.getText();

        Funcionario funcionario = new Funcionario(Integer.parseInt(id), nome, rgf, rg, cpf);
        if(Validar.validarCPF(cpf)){
            new FuncionarioDAO().update(funcionario);
            JOptionPane.showMessageDialog(this, "Funcionário Atualizado");
        } else {
            JOptionPane.showMessageDialog(null, "Preencha os campos corretamente");
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAtualiazarFuncionarioMouseClicked

    private void BtnListarFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnListarFuncionariosMouseClicked

        DefaultTableModel tabelaFuncionarios = (DefaultTableModel) jTable1.getModel();

        Integer numero = tabelaFuncionarios.getRowCount();

        if(numero > 0){
            for(int i = 0; i < numero; i++){
                tabelaFuncionarios.removeRow(0);
            }
            List<Funcionario> funcionarios = new FuncionarioDAO().getFuncionarios();

            for(Funcionario funcionario : funcionarios){
                Object[] dados = {funcionario.getNome(),funcionario.getRgf(),funcionario.getRg(),funcionario.getCpf(),funcionario.getId()};
                tabelaFuncionarios.addRow(dados);
            }
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_BtnListarFuncionariosMouseClicked

    private void BtnDeletarFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDeletarFuncionarioMouseClicked
        String id = TextIDFuncionarios.getText();

        Funcionario funcionario = new Funcionario(Integer.parseInt(id), null, null, null, null);
        new FuncionarioDAO().deleteById(funcionario.getId());

        JOptionPane.showMessageDialog(this, "Deletado com sucesso");


        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDeletarFuncionarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Funcionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdicionarFuncionario;
    private javax.swing.JButton BtnAtualiazarFuncionario;
    private javax.swing.JButton BtnDeletarFuncionario;
    private javax.swing.JButton BtnListarFuncionarios;
    private javax.swing.JLabel CPF;
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel RG;
    private javax.swing.JLabel RGF;
    private javax.swing.JButton Sair;
    private javax.swing.JTextField TextCpfFuncionario;
    private javax.swing.JTextField TextIDFuncionarios;
    private javax.swing.JTextField TextNomeFuncionario;
    private javax.swing.JTextField TextRgFuncionario;
    private javax.swing.JTextField TextRgfFuncionario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
